export const SET_PLACE_ADDRESS = 'SET_PLACE_ADDRESS'

export const SET_FORMATTED_PLACE = 'SET_FORMATTED_PLACE'

export const SET_POSITION = 'SET_POSITION'

export const SET_USER_INFO = 'SET_USER_INFO'
